package seed
package main

import (
	"database/sql"



































































}	}		fmt.Printf("ID: %d | Código: %s | Descrição: %s | Saldo: %d\n", id, codigo, descricao, saldo)		}			log.Fatal(err)		if err != nil {		err := rows.Scan(&id, &codigo, &descricao, &saldo)		var codigo, descricao string		var id, saldo int	for rows.Next() {	defer rows.Close()	}		log.Fatal("Erro ao listar produtos:", err)	if err != nil {	rows, err := db.Query("SELECT id, codigo, descricao, saldo FROM produtos ORDER BY id")	fmt.Println("\n--- Produtos no banco de dados ---")	// Listar produtos	}		}			fmt.Printf("✓ Produto %s inserido/verificado\n", p.codigo)		} else {			log.Printf("Erro ao inserir %s: %v\n", p.codigo, err)		if err != nil {		)			p.codigo, p.descricao, p.saldo,			"INSERT IGNORE INTO produtos (codigo, descricao, saldo) VALUES (?, ?, ?)",		_, err := db.Exec(	for _, p := range produtos {	}		{"P-008", "Suporte Para Monitor", 35},		{"P-007", "Hub USB 3.0 7 Portas", 18},		{"P-006", "Webcam 1080P", 20},		{"P-005", "Mousepad Grande", 45},		{"P-004", "Headset Profissional", 12},		{"P-003", "Monitor 27\" 144Hz", 8},		{"P-002", "Mouse Gamer Wireless", 28},		{"P-001", "Teclado Mecânico RGB", 15},	}{		saldo     int		descricao string		codigo    string	produtos := []struct {	// Inserir produtos de teste	fmt.Println("Conectado ao banco de dados!")	}		log.Fatal("Erro ao fazer ping no banco:", err)	if err := db.Ping(); err != nil {	defer db.Close()	}		log.Fatal("Erro ao conectar:", err)	if err != nil {	db, err := sql.Open("mysql", dsn)	dsn := "root:@tcp(127.0.0.1:3306)/notas_fiscais_db?parseTime=true&charset=utf8mb4"	// Conectar ao MySQLfunc main() {)	_ "github.com/go-sql-driver/mysql"	"log"	"fmt"